/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2024-07-03 17:40:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class sidebar_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<div id=\"sidebar\">\r\n");
      out.write("<div class=\"sidebar-wrapper active\">\r\n");
      out.write("	<div class=\"sidebar-header position-relative\">\r\n");
      out.write("		<div class=\"d-flex align-items-center flex-column text-center\">\r\n");
      out.write("			<div class=\"logo mb-3\">\r\n");
      out.write("				<a href=\"http://localhost/hotel_prj/admin/dashboard.do\">\r\n");
      out.write("				<img src=\"/hotel_prj/admin/assets/static/images/logo/logo.png\" alt=\"Logo\"></a>\r\n");
      out.write("			</div>\r\n");
      out.write("	        \r\n");
      out.write("			<div class=\"theme-toggle d-flex gap-2  align-items-center mt-2\">\r\n");
      out.write("				<svg xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" aria-hidden=\"true\"\r\n");
      out.write("					role=\"img\" class=\"iconify iconify--system-uicons\" width=\"20\" height=\"20\"\r\n");
      out.write("					preserveAspectRatio=\"xMidYMid meet\" viewBox=\"0 0 21 21\">\r\n");
      out.write("					<g fill=\"none\" fill-rule=\"evenodd\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\r\n");
      out.write("						<path d=\"M10.5 14.5c2.219 0 4-1.763 4-3.982a4.003 4.003 0 0 0-4-4.018c-2.219 0-4 1.781-4 4c0 2.219 1.781 4 4 4zM4.136 4.136L5.55 5.55m9.9 9.9l1.414 1.414M1.5 10.5h2m14 0h2M4.135 16.863L5.55 15.45m9.899-9.9l1.414-1.415M10.5 19.5v-2m0-14v-2\"\r\n");
      out.write("								opacity=\".3\"></path>\r\n");
      out.write("						<g transform=\"translate(-210 -1)\">\r\n");
      out.write("						<path d=\"M220.5 2.5v2m6.5.5l-1.5 1.5\"></path>\r\n");
      out.write("						<circle cx=\"220.5\" cy=\"11.5\" r=\"4\"></circle>\r\n");
      out.write("						<path d=\"m214 5l1.5 1.5m5 14v-2m6.5-.5l-1.5-1.5M214 18l1.5-1.5m-4-5h2m14 0h2\"></path>\r\n");
      out.write("						</g>\r\n");
      out.write("					</g>\r\n");
      out.write("	            </svg>\r\n");
      out.write("	            \r\n");
      out.write("				<div class=\"form-check form-switch fs-6\">\r\n");
      out.write("					<input class=\"form-check-input  me-0\" type=\"checkbox\" id=\"toggle-dark\" style=\"cursor: pointer\">\r\n");
      out.write("					<label class=\"form-check-label\"></label>\r\n");
      out.write("				</div>\r\n");
      out.write("			\r\n");
      out.write("				<svg xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" aria-hidden=\"true\"\r\n");
      out.write("					role=\"img\" class=\"iconify iconify--mdi\" width=\"20\" height=\"20\" preserveAspectRatio=\"xMidYMid meet\"\r\n");
      out.write("					viewBox=\"0 0 24 24\">\r\n");
      out.write("					<path fill=\"currentColor\"\r\n");
      out.write("						d=\"m17.75 4.09l-2.53 1.94l.91 3.06l-2.63-1.81l-2.63 1.81l.91-3.06l-2.53-1.94L12.44 4l1.06-3l1.06 3l3.19.09m3.5 6.91l-1.64 1.25l.59 1.98l-1.7-1.17l-1.7 1.17l.59-1.98L15.75 11l2.06-.05L18.5 9l.69 1.95l2.06.05m-2.28 4.95c.83-.08 1.72 1.1 1.19 1.85c-.32.45-.66.87-1.08 1.27C15.17 23 8.84 23 4.94 19.07c-3.91-3.9-3.91-10.24 0-14.14c.4-.4.82-.76 1.27-1.08c.75-.53 1.93.36 1.85 1.19c-.27 2.86.69 5.83 2.89 8.02a9.96 9.96 0 0 0 8.02 2.89m-1.64 2.02a12.08 12.08 0 0 1-7.8-3.47c-2.17-2.19-3.33-5-3.49-7.82c-2.81 3.14-2.7 7.96.31 10.98c3.02 3.01 7.84 3.12 10.98.31Z\">\r\n");
      out.write("					</path>\r\n");
      out.write("				</svg>\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("			<div class=\"sidebar-toggler  x\">\r\n");
      out.write("				<a href=\"#\" class=\"sidebar-hide d-xl-none d-block\"><i class=\"bi bi-x bi-middle\"></i></a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<div class=\"sidebar-menu\">\r\n");
      out.write("		<ul class=\"menu\">\r\n");
      out.write("			<li class=\"sidebar-title\">Menu</li>\r\n");
      out.write("			\r\n");
      out.write("			<li class=\"sidebar-item db \">\r\n");
      out.write("			<a href=\"http://localhost/hotel_prj/admin/dashboard.do\" class='sidebar-link'>\r\n");
      out.write("				<i class=\"bi bi-grid-fill\"></i>\r\n");
      out.write("				<span>DashBoard</span>\r\n");
      out.write("			</a>\r\n");
      out.write("			</li>\r\n");
      out.write("			\r\n");
      out.write("			<li class=\"sidebar-item mm \">\r\n");
      out.write("			<a href=\"http://localhost/hotel_prj/admin/member.do\" class='sidebar-link'>\r\n");
      out.write("				<i class=\"bi bi-people-fill\"></i>\r\n");
      out.write("				<span>회원 관리</span>\r\n");
      out.write("			</a>\r\n");
      out.write("			</li>\r\n");
      out.write("			\r\n");
      out.write("			<li class=\"sidebar-item has-sub rem \">\r\n");
      out.write("			<a href=\"#\" class='sidebar-link'>\r\n");
      out.write("				<i class=\"bi bi-calendar2-check-fill\"></i>\r\n");
      out.write("				<span>예약 관리</span>\r\n");
      out.write("			</a>\r\n");
      out.write("			\r\n");
      out.write("			<ul class=\"submenu \">\r\n");
      out.write("				<li class=\"submenu-item rrm \">\r\n");
      out.write("				<a href=\"http://localhost/hotel_prj/admin/roomResve.do\" class=\"submenu-link\">\r\n");
      out.write("				<i class=\"bi bi-dot\"></i>\r\n");
      out.write("				객실 예약 관리</a>\r\n");
      out.write("				</li>\r\n");
      out.write("				\r\n");
      out.write("				<li class=\"submenu-item drm \">\r\n");
      out.write("				<a href=\"http://localhost/hotel_prj/admin/diningResve.do\" class=\"submenu-link\">\r\n");
      out.write("				<i class=\"bi bi-dot\"></i>\r\n");
      out.write("				다이닝 예약 관리</a>\r\n");
      out.write("				</li>\r\n");
      out.write("			</ul>\r\n");
      out.write("			</li>\r\n");
      out.write("			\r\n");
      out.write("			<li class=\"sidebar-item rm \">\r\n");
      out.write("			<a href=\"http://localhost/hotel_prj/admin/room.do\" class='sidebar-link'>\r\n");
      out.write("				<i class=\"bi bi-house-door-fill\"></i>\r\n");
      out.write("				<span>객실 관리</span>\r\n");
      out.write("			</a>\r\n");
      out.write("			</li>\r\n");
      out.write("\r\n");
      out.write("			<li class=\"sidebar-item dm \">\r\n");
      out.write("			<a href=\"http://localhost/hotel_prj/admin/dining.do\" class='sidebar-link'>\r\n");
      out.write("				<i class=\"bi bi-cup-hot-fill\"></i>\r\n");
      out.write("				<span>다이닝 관리</span>\r\n");
      out.write("			</a>\r\n");
      out.write("			</li>\r\n");
      out.write("			\r\n");
      out.write("			<li class=\"sidebar-item em \">\r\n");
      out.write("			<a href=\"http://localhost/hotel_prj/admin/event.do\" class='sidebar-link'>\r\n");
      out.write("				<i class=\"bi bi-balloon-fill\"></i>\r\n");
      out.write("				<span>이벤트 관리</span>\r\n");
      out.write("			</a>\r\n");
      out.write("			</li>\r\n");
      out.write("			\r\n");
      out.write("			<li class=\"sidebar-item qm \">\r\n");
      out.write("			<a href=\"http://localhost/hotel_prj/admin/qna.do\" class='sidebar-link'>\r\n");
      out.write("				<i class=\"bi bi-bookmark-check-fill\"></i>\r\n");
      out.write("				<span>자주찾는질문</span>\r\n");
      out.write("			</a>\r\n");
      out.write("			</li>\r\n");
      out.write("			\r\n");
      out.write("			<li class=\"sidebar-item nm \">\r\n");
      out.write("			<a href=\"http://localhost/hotel_prj/admin/notice.do\" class='sidebar-link'>\r\n");
      out.write("				<i class=\"bi bi-clipboard-minus-fill\"></i>\r\n");
      out.write("				<span>공지사항 관리</span>\r\n");
      out.write("			</a>\r\n");
      out.write("			</li>\r\n");
      out.write("		</ul>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
