/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2024-07-06 12:18:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.user.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class event_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  public java.lang.String getServletInfo() {
    return "이벤트 화면";
  }

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/dev/workspace_spring/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/hotel_prj/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1716336001598L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, user-scalable=no\">\r\n");
      out.write("    <meta name=\"format-detection\" content=\"telephone=no\">\r\n");
      out.write("    <title>이벤트 이벤트 목록 | 엘리시안호텔</title>\r\n");
      out.write("    <link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"http://localhost/hotel_prj/static/home/images/ko/pc/common/favicon.ico\">\r\n");
      out.write("    <link href=\"http://localhost/hotel_prj/static/home/css/ko/pc/common_josunhotel.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("    <link href=\"http://localhost/hotel_prj/static/home/css/ko/pc/contents.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("    <link href=\"http://localhost/hotel_prj/static/home/bluewaves/css/pc/contents.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("    <link href=\"http://localhost/hotel_prj/static/home/css/ko/pc/swiper.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("    <script type=\"text/javascript\" src=\"http://localhost/hotel_prj/static/home/js/ko/pc/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"http://localhost/hotel_prj/static/home/js/ko/pc/pubPlugin.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"http://localhost/hotel_prj/static/home/js/ko/pc/pubCommon_contents.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"http://localhost/hotel_prj/static/home/js/ko/pc/pubCommon_josunhotel.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"http://localhost/hotel_prj/static/home/js/ko/pc/selectbox.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"http://localhost/hotel_prj/static/home/js/ko/pc/swiper.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"http://localhost/hotel_prj/static/home/js/home.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"http://localhost/hotel_prj/static/home/bluewaves/js/pc/bw_contents.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("  \r\n");
      out.write("</head>\r\n");
      out.write("    <!-- S header -->\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/user/header.jsp", out, false);
      out.write("\r\n");
      out.write("    <!-- E header -->\r\n");
      out.write("<body>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	\r\n");
      out.write("	var page = 1; // 페이지 초기 값\r\n");
      out.write("	var size = 6; // 한 페이지에 6개 이벤트\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("    $(document).ready(function() {\r\n");
      out.write("        var searchDataBeginDe = \"\";\r\n");
      out.write("        var searchDataEndDe = \"\";\r\n");
      out.write("        var searchText = \"\";\r\n");
      out.write("    	//초기 로딩\r\n");
      out.write("    	loadEvents(page, size,searchDataBeginDe,searchDataEndDe,searchText);\r\n");
      out.write("        // 이벤트 목록 더보기 버튼 클릭\r\n");
      out.write("        $(\"#btnMore\").on('click', function(e) {\r\n");
      out.write("            $(\".btnArea\").hide();\r\n");
      out.write("            e.preventDefault(); // 기본 동작 방지\r\n");
      out.write("            loadEvents(++page, size,searchDataBeginDe,searchDataEndDe,searchText); // AJAX를 통해 다음 페이지의 이벤트를 로드\r\n");
      out.write("        });\r\n");
      out.write("        \r\n");
      out.write("	});//ready\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("	function fncSearch() {\r\n");
      out.write("		page = 1;\r\n");
      out.write("    	fncPage(page);\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("    function fncPage(page) {\r\n");
      out.write("        var searchDataBeginDe = $(\"#datepickerFrom\").val();\r\n");
      out.write("        var searchDataEndDe = $(\"#datepickerTo\").val();\r\n");
      out.write("        var searchText = $(\"#searchDataValue\").val();\r\n");
      out.write("		if (searchDataBeginDe != \"\" && searchDataEndDe == \"\") {\r\n");
      out.write("            alert(\"검색 종료일을 입력해 주세요.\");\r\n");
      out.write("            $(\"#datepickerTo\").focus();\r\n");
      out.write("            return;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        if (searchDataBeginDe == \"\" && searchDataEndDe != \"\") {\r\n");
      out.write("            alert(\"검색 시작일을 입력해 주세요.\");\r\n");
      out.write("            $(\"#datepickerFrom\").focus();\r\n");
      out.write("            return;\r\n");
      out.write("        }\r\n");
      out.write("		\r\n");
      out.write("        loadEvents(page, size, searchDataBeginDe, searchDataEndDe,searchText);\r\n");
      out.write("  \r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    function loadEvents(page,size,startDate, endDate,searchText) {\r\n");
      out.write("        //ajax로 이벤트 리스트 비동기 형식으로 얻기\r\n");
      out.write("        $.ajax({\r\n");
      out.write("            type: \"GET\",\r\n");
      out.write("            url: \"eventList.do\",\r\n");
      out.write("            cache: false, \r\n");
      out.write("            data: {\r\n");
      out.write("            	page : page,\r\n");
      out.write("            	size : size,\r\n");
      out.write("            	startDate : startDate,\r\n");
      out.write("            	endDate : endDate,\r\n");
      out.write("            	searchText : searchText}\r\n");
      out.write("            ,\r\n");
      out.write("            dataType: \"json\",\r\n");
      out.write("            global: false,\r\n");
      out.write("            beforeSend: function() {\r\n");
      out.write("                commonJs.showLoadingBar();\r\n");
      out.write("            },\r\n");
      out.write("            complete: function() {\r\n");
      out.write("                commonJs.closeLoadingBar();\r\n");
      out.write("            },\r\n");
      out.write("            success: function(response) {\r\n");
      out.write("                var events = response.events;\r\n");
      out.write("                var totalCount = response.totalCount;\r\n");
      out.write("                var html = \"\";\r\n");
      out.write("                \r\n");
      out.write("                // 페이지 초기화 시 기존 내용을 지움\r\n");
      out.write("                if (page === 1) {\r\n");
      out.write("                    $(\".boxtypeList.eventType\").empty();\r\n");
      out.write("                }\r\n");
      out.write("                \r\n");
      out.write("                if (events.length > 0) {\r\n");
      out.write("                	events.forEach(function(event) {\r\n");
      out.write("                        html += '<li style=\"opacity: 1; transform: matrix(1, 0, 0, 1, 0, 0);\">';\r\n");
      out.write("                        html += '<dl>';\r\n");
      out.write("                        html += '<dt>' + event.eventTitle + '</dt>';\r\n");
      out.write("                        html += '<dd class=\"thum\"><img src=\"http://localhost/hotel_prj/util/event_img/' + event.eventMainImg + '\" alt=\"' + event.eventTitle + '\"></dd>';\r\n");
      out.write("                        html += '<dd class=\"txt\">' + event.eventSubTitle + '</dd>';\r\n");
      out.write("                        html += '<dd class=\"date\">';\r\n");
      out.write("                        html += '<div><span>기간</span><em>' + event.eventStartDate + ' - ' + event.eventEndDate + '</em></div>';\r\n");
      out.write("                        html += '</dd>';\r\n");
      out.write("                        html += '</dl>';\r\n");
      out.write("                        html += '<div class=\"btn\">';\r\n");
      out.write("                        html += '<a href=\"http://localhost/hotel_prj/user/eventDetail.do?eventNum=' + event.eventNum + '\" class=\"btnSC btnM active\" id=\"event_see_detail\" \">자세히 보기</a>';\r\n");
      out.write("                        html += '</div>';\r\n");
      out.write("                        html += '</li>';\r\n");
      out.write("                    });\r\n");
      out.write("\r\n");
      out.write("                    $(\".boxtypeList.eventType\").append(html);\r\n");
      out.write("                }\r\n");
      out.write("				\r\n");
      out.write("                //페이지 * 사이즈가 리스트전체개수와\r\n");
      out.write("                if (page * size >= totalCount) {\r\n");
      out.write("                    $(\".btnArea\").hide();\r\n");
      out.write("                } else {\r\n");
      out.write("                    $(\".btnArea\").show();\r\n");
      out.write("                }\r\n");
      out.write("            },\r\n");
      out.write("            error: function(xhr, status, error) {\r\n");
      out.write("                console.log('Status:', status);\r\n");
      out.write("                console.log('Error:', error);\r\n");
      out.write("                console.log('Response:', xhr.responseText);\r\n");
      out.write("                // 응답이 HTML일 경우, JSON으로 파싱할 수 없어서 오류가 발생할 수 있습니다.\r\n");
      out.write("                if (xhr.responseText.startsWith('<')) {\r\n");
      out.write("                    console.log('HTML 응답이 반환되었습니다. 서버 측의 응답을 확인하세요.');\r\n");
      out.write("                }\r\n");
      out.write("                alert('이벤트 목록을 불러오는 중 오류가 발생했습니다.');\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<div class=\"wrapper\">\r\n");
      out.write("\r\n");
      out.write("    <form id=\"form\" name=\"form\">\r\n");
      out.write("        <input type=\"hidden\" id=\"page\" name=\"page\" value=\"1\" />\r\n");
      out.write("        <input type=\"hidden\" id=\"rowPerPage\" name=\"rowPerPage\" value=\"6\" />\r\n");
      out.write("        <input type=\"hidden\" id=\"totalCount\" name=\"totalCount\" value=\"20\" />\r\n");
      out.write("        <input type=\"hidden\" id=\"searchDataType\" name=\"searchDataType\" />\r\n");
      out.write("        <input type=\"hidden\" id=\"eventSn\" name=\"eventSn\" value=\"\" />\r\n");
      out.write("        <input type=\"hidden\" id=\"sysCode\" value=\"JOSUNHOTEL\"/>\r\n");
      out.write("\r\n");
      out.write("        <div id=\"container\" class=\"container\">\r\n");
      out.write("            <!-- 컨텐츠 S -->\r\n");
      out.write("            <h1 class=\"hidden\">Promotion</h1>\r\n");
      out.write("            <div class=\"topArea\">\r\n");
      out.write("                <div class=\"topInner\">\r\n");
      out.write("                    <h2 class=\"titDep1\">Promotion</h2>\r\n");
      out.write("                    <p class=\"pageGuide\">\r\n");
      out.write("                        조선호텔앤리조트의 특별한 이벤트를 놓치지 마세요.    \r\n");
      out.write("                    </p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- 이벤트 검색 박스 -->\r\n");
      out.write("            <div class=\"searchBox package\">\r\n");
      out.write("                <div class=\"inner\">\r\n");
      out.write("                    <div class=\"searchOp\">\r\n");
      out.write("                        <div class=\"period\">\r\n");
      out.write("                            <span class=\"hidden\">날짜선택</span>\r\n");
      out.write("                            <span class=\"intArea\">\r\n");
      out.write("                                <input type=\"text\" value=\"\" name=\"searchDataBeginDe\" style='width:200px' placeholder=\"YYYY-MM-DD\" title=\"검색 시작일\" readonly id=\"datepickerFrom\">\r\n");
      out.write("                            </span>\r\n");
      out.write("                            <span class=\"hBar\">-</span>\r\n");
      out.write("                            <span class=\"intArea\">\r\n");
      out.write("                                <input type=\"text\" value=\"\" name=\"searchDataEndDe\" style='width:200px' placeholder=\"YYYY-MM-DD\" title=\"검색 종료일\" readonly id=\"datepickerTo\">\r\n");
      out.write("                            </span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"intWord\">\r\n");
      out.write("                            <span class=\"intArea\">\r\n");
      out.write("                                <input type=\"text\" style='width:376px' id=\"searchDataValue\" name=\"searchDataValue\" value=\"\" title=\"검색어 입력\" placeholder=\"검색어를 입력해주세요.\">\r\n");
      out.write("                            </span>\r\n");
      out.write("                            <button type=\"button\" class=\"btnSC btnM\" onclick=\"fncSearch();\">검색</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- //searchBox -->\r\n");
      out.write("\r\n");
      out.write("            <!-- 이벤트 목록 -->\r\n");
      out.write("            <div class=\"inner\">\r\n");
      out.write("                <ul class=\"boxtypeList parallaxUp eventType\">\r\n");
      out.write("                    <!-- 이벤트 항목이 동적으로 추가됩니다. -->\r\n");
      out.write("                </ul>\r\n");
      out.write("                <div class=\"btnArea\">\r\n");
      out.write("                    <a href=\"#\" class=\"btnSC btnMore\" id=\"btnMore\">MORE</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- //inner -->\r\n");
      out.write("        </div> <!-- container div의 닫는 태그 추가 -->\r\n");
      out.write("    </form>\r\n");
      out.write("\r\n");
      out.write("    <!-- S footer -->\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/user/footer.jsp", out, false);
      out.write("\r\n");
      out.write("    <!-- E footer -->\r\n");
      out.write("</div>\r\n");
      out.write("<!-- //wrapper -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
