/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2024-07-11 09:05:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.user.resve.dining;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class complete_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  public java.lang.String getServletInfo() {
    return "";
  }

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/C:/dev/workspace_spring/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/hotel_prj/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/C:/dev/workspace_spring/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/hotel_prj/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1716336001598L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- view-source:https://www.josunhotel.com/resve/dining/complete.do?reservationId=zfRwJnbl7cF6OEiZ6uQo0w-->\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, user-scalable=no\">\r\n");
      out.write("<meta name=\"format-detection\" content=\"telephone=no\">\r\n");
      out.write("\r\n");
      out.write("<title>다이닝 예약 - 예약 완료 | 엘리시안호텔</title>\r\n");
      out.write("\r\n");
      out.write("<!-- S head css -->\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/user/common/head_css.jsp", out, false);
      out.write("\r\n");
      out.write("<link href=\"http://localhost/hotel_prj/static/home/css/ko/pc/contents.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<!-- E head css -->\r\n");
      out.write("<style>\r\n");
      out.write(".listTit{\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	color: #006400; \r\n");
      out.write("}\r\n");
      out.write(" .listTit::before {\r\n");
      out.write("        content: '•';\r\n");
      out.write("        color: #006400; /* 진한 초록색 점 */\r\n");
      out.write("        margin-right: 5px; /* 점과 글자 사이의 간격 */\r\n");
      out.write("  }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"wrapper \">\r\n");
      out.write("<script>\r\n");
      out.write("        //헤더 메뉴 버튼 클릭 이벤트\r\n");
      out.write("        jQuery(document).on(\"click\",\".headArea .btnMenu\" ,function(){\r\n");
      out.write("\r\n");
      out.write("            //메뉴 펼쳐질때 라운지 list 3가지 무작위 노출\r\n");
      out.write("            if(jQuery(this).hasClass(\"menuOn\")){\r\n");
      out.write("                var expsrCount = 3;\r\n");
      out.write("                var $loungeList = jQuery(\".menuDepth-add .gnb-thum li\");\r\n");
      out.write("                var randomArray = generateRandomNumberArray(expsrCount, $loungeList.length);\r\n");
      out.write("\r\n");
      out.write("                $loungeList.addClass(\"hidden\");\r\n");
      out.write("                $loungeList.each(function(index){\r\n");
      out.write("                    if(randomArray.indexOf(index) > -1){\r\n");
      out.write("                        jQuery(this).removeClass(\"hidden\");\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("            }\r\n");
      out.write("        })\r\n");
      out.write("</script>\r\n");
      out.write("<!--S header  -->\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/user/header.jsp", out, false);
      out.write("\r\n");
      out.write("<!--E header  -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"container\" class=\"container\">\r\n");
      out.write("    <!-- 컨텐츠 S -->\r\n");
      out.write("    <h1 class=\"hidden\">예약</h1>\r\n");
      out.write("	<div class=\"topArea\">\r\n");
      out.write("		<div class=\"topInner\">\r\n");
      out.write("			<p class=\"f75\">예약이 완료되었습니다.</p>\r\n");
      out.write("			<div class=\"revNumber\">예약번호<em>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${drInfoVO.payNum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</em></div>\r\n");
      out.write("			<p class=\"pageGuide\">요청하신 예약은 정상적으로 처리되었으며, 예약번호는 예약 조회 및 취소 시<br> 반드시 필요하니, 프린트 또는 메모해 주시기 바랍니다.</p>\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("    <!-- //topArea -->\r\n");
      out.write("    <div class=\"inner\">\r\n");
      out.write("        <h2 class=\"titDep2\">예약 정보 </h2>\r\n");
      out.write("        <div class=\"commWrap rsvInfo drDining_st04\">\r\n");
      out.write("            <dl class=\"commlist\">\r\n");
      out.write("                <dt>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${drInfoVO.diningName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</dt>\r\n");
      out.write("                <dd>\r\n");
      out.write("                    <span class=\"txt\">엘리시안 호텔 ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${drInfoVO.location}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("                    <span class=\"thum\"><img src=\"http://localhost/hotel_prj/util/dining_img/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${drInfoVO.diningImg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"></span>\r\n");
      out.write("                </dd>\r\n");
      out.write("            </dl>\r\n");
      out.write("            <dl class=\"commlist\">\r\n");
      out.write("                <dt>예약 상세 정보 </dt>\r\n");
      out.write("	            <dd>\r\n");
      out.write("                    <span class=\"txt visitDate\" >날짜 : ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${drInfoVO.visitDate}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("                    <span class=\"txt visitDateTime\" >시간 : ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${drInfoVO.visitDateTime }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("                    <span class=\"txt person\" ></span>\r\n");
      out.write("                </dd>\r\n");
      out.write("                <dt>추가 요청사항 </dt>\r\n");
      out.write("                <dd>\r\n");
      out.write("                    <span class=\"txt requests\" >");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${drInfoVO.requests }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("                </dd>\r\n");
      out.write("            </dl>\r\n");
      out.write("            <dl class=\"commlist\">\r\n");
      out.write("                <dt>고객 정보 </dt>\r\n");
      out.write("	            <dd>\r\n");
      out.write("	            	<strong class=\"listTit\">예약자</strong>\r\n");
      out.write("                    <span class=\"txt bookerName\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${drInfoVO.bookerName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" 님</span>\r\n");
      out.write("                    <span class=\"txt bookerPhone\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${drInfoVO.bookerPhone}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("                    <span class=\"txt bookerEmail\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${drInfoVO.bookerEmail}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("                </dd>\r\n");
      out.write("	            <br>\r\n");
      out.write("                <dd>\r\n");
      out.write("                	<strong class=\"listTit\">방문자</strong>\r\n");
      out.write("                    <span class=\"txt visitorName\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${drInfoVO.vistorName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" 님</span>\r\n");
      out.write("                    <span class=\"txt visitorPhone\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${drInfoVO.visitorPhone}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("                </dd>\r\n");
      out.write("            </dl>\r\n");
      out.write("            <dl class=\"commlist depositArea\">\r\n");
      out.write("                <dt>결제 예약금 </dt>\r\n");
      out.write("                <dd>\r\n");
      out.write("                    <span class=\"txt deposit\" >");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${drInfoVO.totalPrice}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" KRW</span>\r\n");
      out.write("                </dd>\r\n");
      out.write("            </dl>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"btnArea\">\r\n");
      out.write("            <a href=\"http://localhost/hotel_prj/user/index.do\" class=\"btnSC btnL\">메인 </a>\r\n");
      out.write("            \r\n");
      out.write("                <a href=\"http://localhost/hotel_prj/user/diningResList.do\" class=\"btnSC btnL active\">예약내역 확인<!-- 예약내역 확인 --></a>\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- //inner -->\r\n");
      out.write("    <!-- 컨텐츠 E -->\r\n");
      out.write("</div>\r\n");
      out.write("<!-- //wrapper -->	\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--S footer  -->\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/user/footer.jsp", out, false);
      out.write("\r\n");
      out.write("<!--E footer  -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- //wrapper -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
