/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2024-07-04 05:32:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  public java.lang.String getServletInfo() {
    return "";
  }

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1716336001598L));
    _jspx_dependants.put("jar:file:/C:/dev/workspace_spring/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/spring_mvc/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"icon\" href=\"http://211.63.89.150/spring_mvc/common/favicon.ico\">\r\n");
      out.write("<!-- bootstrap 시작 -->\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH\" crossorigin=\"anonymous\">\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<!-- bootstrap 끝 -->\r\n");
      out.write("<!--sist스타일시트 시작-->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"http://211.63.89.150/spring_mvc/common/css/main.css\" type=\"text/css\" media=\"all\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"http://211.63.89.150/spring_mbv/common/css/board.css\" type=\"text/css\" media=\"all\" />\r\n");
      out.write("<!--sist스타일시트 끝-->\r\n");
      out.write("<!-- JQUERY CDN 시작-->\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js\"></script>\r\n");
      out.write("<!--JQUERY CDN 끝-->\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("	\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	$(function(){\r\n");
      out.write("		$(\"#btnGet\").click(function(){\r\n");
      out.write("			location.href=\"http://localhost/spring_mvc/get.do\";\r\n");
      out.write("		})//click\r\n");
      out.write("		\r\n");
      out.write("		$(\"#btnGetSubmit\").click(function(){\r\n");
      out.write("			$(\"#frmGet\").submit();\r\n");
      out.write("		})//click\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		$(\"#btnPostSubmit\").click(function(){\r\n");
      out.write("			$(\"#frmPost\").submit();\r\n");
      out.write("		})//click\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		$(\"#btnGet2\").click(function(){\r\n");
      out.write("			$(\"#frmGetPost\")[0].method=\"GET\";\r\n");
      out.write("			alert($(\"#frmGetPost\")[0].method);\r\n");
      out.write("		})//click\r\n");
      out.write("		$(\"#btnPost2\").click(function(){\r\n");
      out.write("			$(\"#frmGetPost\")[0].method=\"POST\";\r\n");
      out.write("			alert($(\"#frmGetPost\")[0].method);\r\n");
      out.write("		})//click\r\n");
      out.write("	\r\n");
      out.write("	}); //ready\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div>\r\n");
      out.write("	<div>\r\n");
      out.write("		<h3>GET방식의 요청</h3>\r\n");
      out.write("		<div>\r\n");
      out.write("		<a href=\"get.do\">링크요청</a><br/>\r\n");
      out.write("		<input type=\"button\" value=\"JS loaction요청\" id=\"btnGet\"/><br/>\r\n");
      out.write("		<form action=\"get.do\" method=\"get\" id=\"frmGet\"><br/>\r\n");
      out.write("		<input type=\"button\" class=\"btn btn-success btn-sm\" value=\"GET요청\" id=\"btnGetSubmit\"/>\r\n");
      out.write("		</form>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("===================================================================\r\n");
      out.write("	<div>\r\n");
      out.write("		<h3>POST방식의 요청</h3>\r\n");
      out.write("		<div>\r\n");
      out.write("		<form action=\"post.do\" method=\"post\" id=\"frmPost\">\r\n");
      out.write("		<input type=\"button\" class=\"btn btn-success btn-sm\" value=\"POST요청\" id=\"btnPostSubmit\"/>\r\n");
      out.write("		</form>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("===================================================================\r\n");
      out.write("</div>\r\n");
      out.write("	<div>\r\n");
      out.write("		<ul>\r\n");
      out.write("			<li><a href=\"day0604/param_frm.do\">파라메터 연습</a></li>\r\n");
      out.write("		</ul>\r\n");
      out.write("	</div>\r\n");
      out.write("<div>\r\n");
      out.write("==================================================================== \r\n");
      out.write("<div>\r\n");
      out.write("	<a href=\"a.do\">a.do 연습</a>\r\n");
      out.write("	<a href=\"b.do\">b.do 연습</a>\r\n");
      out.write("	<a href=\"yana.do\">yana.do 연습</a>\r\n");
      out.write("</div>\r\n");
      out.write("==================================================================== \r\n");
      out.write("\r\n");
      out.write("<div>\r\n");
      out.write("	<ul>\r\n");
      out.write("		<li><a href=\"day0605/hsr_hs.do\">Controller에서 View전달</a></li>\r\n");
      out.write("		<li><a href=\"day0605/model.do\">model을 사용하여 view전달</a></li>\r\n");
      out.write("		<li><a href=\"/day0605/mav.do\">model and view 사용</a></li>\r\n");
      out.write("	</ul>\r\n");
      out.write("</div>\r\n");
      out.write("==================================================================== \r\n");
      out.write("<div>\r\n");
      out.write("	<ul>\r\n");
      out.write("		<li><a href=\"day0610/test.jsp\">JSP 호출</a></li>\r\n");
      out.write("		<li><a href=\"day0610/use_redirect.do\">컨트롤러를 통해서 redirect로 jsp 호출</a></li>\r\n");
      out.write("		<li><a href=\"day0610/use_redirect2.do\">\r\n");
      out.write("Controller통해서 redirect로 /day0605/hsr_hs.do호출</a></li>\r\n");
      out.write("		\r\n");
      out.write("	</ul>\r\n");
      out.write("</div>\r\n");
      out.write("==================================================================== \r\n");
      out.write("<div>\r\n");
      out.write("	<ul>\r\n");
      out.write("		<li><a href=\"day0610/forward_a.do?year=2024\">a.do 호출 => b.do => c.do</a></li>\r\n");
      out.write("		<li><a href=\"day0610/forward_a.do?year=2024\">a.do 호출 => b.do => c.do</a></li>\r\n");
      out.write("		<li><a href=\"day0610/forward_b.do?month=6\">b.do => c.do</a></li>\r\n");
      out.write("	</ul>\r\n");
      out.write("</div>\r\n");
      out.write("==================================================================== \r\n");
      out.write("<div>\r\n");
      out.write("	<ul>\r\n");
      out.write("		<li><a href=\"day0610/jsp_include.do?name=dongsub.kim\">jsp include</a></li>\r\n");
      out.write("		<li><a href=\"day0610/temp.do?name=ddinghwa\">temp.do 요청</a></li>\r\n");
      out.write("		<li><a href=\"day0610/do_include.do?name=suyeon.choi\">do include</a></li>\r\n");
      out.write("	</ul>\r\n");
      out.write("</div>\r\n");
      out.write("==================================================================== \r\n");
      out.write("<div>\r\n");
      out.write("	<ul>\r\n");
      out.write("		<li><a href=\"day0610/set_session.do\">세션 값 설정</a></li>\r\n");
      out.write("		<li><a href=\"day0610/get_session.do\">세션 값 얻기</a></li>\r\n");
      out.write("		<li><a href=\"day0610/remove_session.do\">HttpSession 세션사용 종료(삭제안됨)</a></li>\r\n");
      out.write("		<li><a href=\"day0610/remove_session2.do\">SessionStatus세션사용 종료</a></li>\r\n");
      out.write("	</ul>\r\n");
      out.write("</div>\r\n");
      out.write("==================================================================== \r\n");
      out.write("<div>\r\n");
      out.write("	<ul>\r\n");
      out.write("		<li><a href=\"day0610/add_cookie.do\">쿠키 값 설정</a></li>\r\n");
      out.write("		<li><a href=\"day0610/cookie_annotation.do\">@CookieValue 얻기</a></li>\r\n");
      out.write("		<li><a href=\"day0610/web_utils.do\">WebUtils 값 얻기 </a></li>\r\n");
      out.write("	</ul>\r\n");
      out.write("</div>\r\n");
      out.write("==================================================================== \r\n");
      out.write("<div>\r\n");
      out.write("	<ul>\r\n");
      out.write("		<li><a href=\"day0611/ajax.do\">AJAX사용</a></li>\r\n");
      out.write("	</ul>\r\n");
      out.write("</div>\r\n");
      out.write("==================================================================== \r\n");
      out.write("<div>\r\n");
      out.write("	<ul>\r\n");
      out.write("		<li><a href=\"day0611/test_exception.do\">Controller에서 예외발생</a></li>\r\n");
      out.write("		<li><a href=\"day0611/test_exception2.do\">Controller에서 예외발생</a></li>\r\n");
      out.write("	</ul>\r\n");
      out.write("</div>\r\n");
      out.write("==================================================================== \r\n");
      out.write("<div>\r\n");
      out.write("	<ul>\r\n");
      out.write("		<li><a href=\"day0612/err_404.do\">404</a></li>\r\n");
      out.write("		<li>\r\n");
      out.write("			<form action=\"day0612/err_405.do\" method=\"get\">\r\n");
      out.write("				<input type=\"submit\" value=\"POST요청\" class=\"btn btn-success btn-sm\">\r\n");
      out.write("			</form>\r\n");
      out.write("		</li>\r\n");
      out.write("		<li><a href=\"day0612/err_500.do\">500</a></li>\r\n");
      out.write("	</ul>\r\n");
      out.write("</div>\r\n");
      out.write("==================================================================== \r\n");
      out.write("<div>\r\n");
      out.write("	<ul>\r\n");
      out.write("		<li><a href=\"day0613/file_upload_frm.do\">파일업로드</a></li>\r\n");
      out.write("	</ul>\r\n");
      out.write("</div>\r\n");
      out.write("==================================================================== \r\n");
      out.write("<div>\r\n");
      out.write("	<ul>\r\n");
      out.write("		<li><a href=\"day0613/mybatis_search.do?deptno=10\">10번 DB조회</a></li>\r\n");
      out.write("		<li><a href=\"day0613/mybatis_search.do?deptno=20\">20번 DB조회</a></li>\r\n");
      out.write("		<li><a href=\"day0613/mybatis_search.do?deptno=30\">30반 DB조회</a></li>\r\n");
      out.write("	</ul>\r\n");
      out.write("</div>\r\n");
      out.write("==================================================================== \r\n");
      out.write("<div>\r\n");
      out.write("	<ul>\r\n");
      out.write("	\r\n");
      out.write("		<li>\r\n");
      out.write("			<form action=\"day0614/login_process.do\" method=\"post\">'\r\n");
      out.write("			<label>id</label>\r\n");
      out.write("			<input type=\"text\" name=\"id\"/>\r\n");
      out.write("			<label>pass</label>\r\n");
      out.write("			<input type=\"password\" name=\"pass\"/>\r\n");
      out.write("			<label>id</label>\r\n");
      out.write("			<input type=\"submit\" value=\"로그인\" class=\"btn btn-success btn-sm\"/>\r\n");
      out.write("			</form>\r\n");
      out.write("		</li>\r\n");
      out.write("		<li><a href=\"day0614/plain_text.do\">복호화</a></li>\r\n");
      out.write("	</ul>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
